{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Here are some details about the template.",
  "Metadata":
    {
      "AWS::CloudFormation::Designer":
        {
          "12d7e160-0a80-41e1-9076-14d9d321b425":
            {
              "size": { "width": 60, "height": 60 },
              "position": { "x": 150, "y": 60 },
              "z": 1,
              "embeds": [],
              "isassociatedwith": ["75ee4d4d-5387-4e64-a6e7-df69e2be9de2"],
              "dependson": ["af0c845b-f4f3-4d92-9488-ab4306d11151"],
            },
          "75ee4d4d-5387-4e64-a6e7-df69e2be9de2":
            {
              "size": { "width": 60, "height": 60 },
              "position": { "x": 300, "y": 60 },
              "z": 1,
              "embeds": [],
            },
          "0f44b41f-d758-4479-8a37-4cb92468693d":
            {
              "size": { "width": 60, "height": 60 },
              "position": { "x": 60, "y": 60 },
              "z": 1,
              "embeds": [],
            },
          "af0c845b-f4f3-4d92-9488-ab4306d11151":
            {
              "size": { "width": 60, "height": 60 },
              "position": { "x": 250, "y": 190 },
              "z": 1,
              "embeds": [],
            },
          "5712b969-bb67-4153-86de-353b6b1b6e93":
            {
              "size": { "width": 60, "height": 60 },
              "position": { "x": 390, "y": 90 },
              "z": 1,
              "embeds": [],
            },
        },
    },
  "Resources":
    {
      "DBSecret":
        {
          "Type": "AWS::SecretsManager::Secret",
          "Properties":
            {
              "Description": "This is the secret for the PipeBird instance",
              "GenerateSecretString":
                {
                  "SecretStringTemplate": '{"username": "pipebird"}',
                  "GenerateStringKey": "password",
                  "PasswordLength": 32,
                  "ExcludeCharacters": "\"@/\\",
                },
            },
          "Metadata":
            {
              "AWS::CloudFormation::Designer":
                { "id": "5712b969-bb67-4153-86de-353b6b1b6e93" },
            },
        },
      "PipeBirdSecurityGroup":
        {
          "Type": "AWS::EC2::SecurityGroup",
          "Properties":
            {
              "VpcId": { "Ref": "VPC" },
              "GroupDescription": "Enable the ports pipebird requires (80, 22, 3000)",
              "SecurityGroupIngress":
                [
                  {
                    "IpProtocol": "tcp",
                    "FromPort": 80,
                    "ToPort": 80,
                    "CidrIp": "0.0.0.0/0",
                  },
                  {
                    "IpProtocol": "tcp",
                    "FromPort": 22,
                    "ToPort": 22,
                    "CidrIp": "0.0.0.0/0",
                  },
                  {
                    "IpProtocol": "tcp",
                    "FromPort": 3000,
                    "ToPort": 3000,
                    "CidrIp": "0.0.0.0/0",
                  },
                ],
              "SecurityGroupEgress":
                [
                  {
                    "IpProtocol": "tcp",
                    "FromPort": 0,
                    "ToPort": 65535,
                    "CidrIp": "0.0.0.0/0",
                  },
                ],
            },
          "Metadata":
            {
              "AWS::CloudFormation::Designer":
                { "id": "75ee4d4d-5387-4e64-a6e7-df69e2be9de2" },
            },
        },
      "PipeBirdStorage":
        {
          "Type": "AWS::EC2::Volume",
          "Properties":
            {
              "AvailabilityZone": { "Fn::Select": ["0", { "Fn::GetAZs": "" }] },
              "Size": "100",
            },
          "Metadata":
            {
              "AWS::CloudFormation::Designer":
                { "id": "0f44b41f-d758-4479-8a37-4cb92468693d" },
            },
        },
      "PipeBirdInstance":
        {
          "Type": "AWS::EC2::Instance",
          "Metadata":
            {
              "AWS::CloudFormation::Designer":
                { "id": "12d7e160-0a80-41e1-9076-14d9d321b425" },
            },
          "Properties":
            {
              "SubnetId": { "Ref": "subnetId" },
              "UserData":
                {
                  "Fn::Base64":
                    {
                      "Fn::Join":
                        [
                          "\n",
                          [
                            "#!/bin/bash -xe",
                            "sudo apt-get update -y",
                            "sudo apt install unzip",
                            "sudo wget https://github.com/Realize-Engineering/pipebird/archive/refs/heads/main.zip",
                            "unzip main.zip",
                            'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose',
                            "sudo chmod +x /usr/local/bin/docker-compose",
                            "touch .env",
                            'echo "PORT=3000" >> .env',
                            {
                              "Fn::Sub":
                                [
                                  'echo "DATABASE_URL=${DATABASE_URL}" >> .env',
                                  {
                                    "DATABASE_URL":
                                      {
                                        "Fn::Sub":
                                          [
                                            "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public",
                                            {
                                              "POSTGRES_PASSWORD":
                                                { "Ref": "DBSecret" },
                                              "POSTGRES_USER": "pipebird",
                                              "POSTGRES_DB": "pipebird",
                                            },
                                          ],
                                      },
                                  },
                                ],
                            },
                            'echo "REDIS_HOST=localhost" >> .env',
                            'echo "REDIS_PORT=6379" >> .env',
                            'echo "SECRET_KEY=$(openssl rand -hex 32)" >> .env',
                            'echo "S3_USER_ACCESS_ID=$()" >> .env',
                            'echo "S3_USER_SECRET_KEY=$()" >> .env',
                            'echo "PROVISIONED_BUCKET_NAME=ProvisionedPipeBirdBucket" >> .env',
                            {
                              "Fn::Sub":
                                [
                                  'echo "AWS_REGION=${AWS_REGION}" >> .env',
                                  { "AWS_REGION": { "Ref": "AWS::Region" } },
                                ],
                            },
                            "mv .env pipebird-main",
                            "cd pipebird-main && docker-compose up",
                          ],
                        ],
                    },
                },
              "KeyName": { "Ref": "ec2KeyPair" },
              "Tags": [{ "Key": "Name", "Value": "PipeBird" }],
              "ImageId": "ami-052efd3df9dad4825",
              "AvailabilityZone": { "Fn::Select": ["0", { "Fn::GetAZs": "" }] },
              "InstanceType": "t2.medium",
              "BlockDeviceMappings":
                [{ "DeviceName": "/dev/sda1", "Ebs": { "VolumeSize": "50" } }],
              "SecurityGroupIds": [{ "Ref": "PipeBirdSecurityGroup" }],
            },
          "CreationPolicy": { "ResourceSignal": { "Timeout": "PT30M" } },
          "DependsOn": ["ProvisionedPipeBirdBucket", "DBSecret"],
        },
      "ProvisionedPipeBirdBucket":
        {
          "Type": "AWS::S3::Bucket",
          "Properties": {},
          "Metadata":
            {
              "AWS::CloudFormation::Designer":
                { "id": "af0c845b-f4f3-4d92-9488-ab4306d11151" },
            },
        },
    },
  "Parameters":
    {
      "ec2KeyPair":
        {
          "Description": "Key pair to access the box running PipeBird",
          "Type": "AWS::EC2::KeyPair::KeyName",
        },
      "VPC":
        {
          "Description": "The VPC to run pipebird inside of",
          "Type": "AWS::EC2::VPC::Id",
        },
      "licenseKey":
        {
          "Description": "License Key for your pipebird deployment. Get yours at my.pipebird.com",
          "Type": "String",
        },
      "subnetId":
        {
          "Description": "Subnet id to deploy ec2 in within your vpc.",
          "Type": "String",
        },
    },
  "Outputs":
    {
      "YourPipeBirdIP":
        {
          "Description": "IP address for your self-hosted PipeBird instance. Get started by signing up here!",
          "Value":
            {
              "Fn::Join":
                [
                  "",
                  [
                    "http://",
                    { "Fn::GetAtt": ["PipeBirdInstance", "PublicIp"] },
                    ":3000",
                  ],
                ],
            },
        },
    },
}
